<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findReclamation($input)
    {
        $query=$this->getEntityManager()->createQuery("SELECT f FROM ReclamationBundle:Reclamations f 
WHERE f.reponse='$input'");
        return $query->getResult();
    }

}
