<?php

namespace GradeBundle\Repository;

/**
 * classeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClasseRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindAll($input)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT c FROM GradeBundle:Classe c WHERE c.nomclasse = '$input'");
        return $query->getResult();
    }




}
