<?php

namespace MedcinBundle\Repository;

/**
 * consultationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class consultationRepository extends \Doctrine\ORM\EntityRepository
{
}
