<?php

namespace MedcinBundle\Repository;

/**
 * dossier_medicaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dossier_medicaleRepository extends \Doctrine\ORM\EntityRepository
{
}
