reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /reclamation


inventaire:
    resource: "@InventaireBundle/Resources/config/routing.yml"
    prefix: /inventaire

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller'
    type: annotation




