

inventaire_homepage:
    path:     /index
    defaults: { _controller: InventaireBundle:Default:index }

create_enseignant:
    path:     /admin/createEnseignant
    defaults: { _controller: InventaireBundle:Enseignant:create }

delete_enseignant:
    path:     /delete/{id}
    defaults: { _controller: InventaireBundle:Enseignant:delete }

read_enseignant:
    path:     /admin/readEnseignant
    defaults: { _controller: InventaireBundle:Enseignant:read }

update_enseignant:
    path:     /updateEnseignant/{id}
    defaults: { _controller: InventaireBundle:Enseignant:update }




read_salaire:
    path:     /readSalaire
    defaults: { _controller: InventaireBundle:salaire:read }

update_salaire:
    path:     /update/{id}
    defaults: { _controller: InventaireBundle:salaire:update }



create_e:
    path:     /createSalaire
    defaults: { _controller: InventaireBundle:salaire:create }

delete_salaire:
    path:     /deleteSalaire/{id}
    defaults: { _controller: InventaireBundle:salaire:delete }


